version: 2

jobs:
  build:
    #...
    machine:
      enabled: true
    steps:
      - run:
          name: Build
          command: |
            echo "Hello CI"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST bash -c '\
            echo "Got In"
            echo "say hi"
            exit'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: circleci-project-setup # only deploy on the master branch
