version: 2

jobs:
  build:
    #...
    machine:
      enabled: true
    steps:
      - run:
          name: Build
          command: |
            echo "You know you should write tests, right?"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST bash -c '\

            # Screaming that I got in!
            echo "Got in, yay!!"

            # Going into the project folder
            cd /app/area-search-engine/

            # Pulling in the master repo
            git pull origin master

            # Running deploy specific commands
            chmod +x ./deploy.sh
            ./deploy.sh

            # Getting out of the vm instance
            exit'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch
